export { default as HomePage } from './HomePage.jsx';
export { default as Login } from './Login.jsx';
export { default as AdminPanel } from './AdminPanel.jsx';
export { default as FriendPanel } from './FriendPanel.jsx';
export { default as Register } from './Register.jsx';
export { default as EditSpecie } from './EditSpecie.jsx';
export { default as AddSpecie } from './AddSpecie.jsx'; 
export { default as AddTree } from './AddTree.jsx'; 
export { default as FriendTrees } from './FriendTrees.jsx';
export { default as EditTree } from './EditTree.jsx';
export { default as UpdateTrees}  from './UpdateTrees.jsx'; 
export { default as OperatorPanel}  from './OperatorPanel.jsx';
export { default as AddUser } from './AddUser.jsx'; 
